### ISSUE TITLE
CSS changes

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#100]
Some color changes:

All buttons in the work spaces (Save, Add New, etc.): These are now an intense blue, make them black background instead, keep white letters.  Use the color of the mouseover on the title bar menu items, if not black.  Also make the export symbol the same color, or something that fits in more, a gray or brown-gray.

Planning page colors, to pick up the title image colors and unify the scheme a bit:
* The production columns background, now a gray, make them a different gray: BFBFBF.
* The offers and requests columns background, now a light blue, make them 8C8C8C.
* The satisfy requests column background, now the light blue, make it CFBAAS.
* The offers and requests inside shapes (the proposals/intents), make the background of those a light blue, let's try the color of the current background.  If too dark for the black lettering, we can lighten them up.

Note: This was initiated by me (users agreed but did not initiate), so please feel free to disagree, or let me know if any of this takes much time.  If you want me to get in a call when you do it, let me know.

**Comment by LeosPrograms** [comment]
The color #CFBAAS doesn't appear to exist.

**Comment by LeosPrograms** [comment]
I don't think blue looks good as a background for offers/requests.

**Comment by fosterlynn** [comment]
>The color #CFBAAS doesn't appear to exist.

I was trying for a lighter column background in the same brown-gray area.  Feel free to pick one you like; or we can just use either of the other column background colors, as long as the offers/requests are a color.

>I don't think blue looks good as a background for offers/requests.

OK.  I think we just need something not already used, so not white, yellow, red, green.  But in that intensity range, kind of.  Do you want to pick another one?  Or we can get on a call if you'd rather.

**Comment by fosterlynn** [comment]
>I was trying for a lighter column background in the same brown-gray area.

How does EEEEEE look?

**Comment by fosterlynn** [comment]
> I think we just need something not already used, so not white, yellow, red, green.

Or, do you think leaving the offers/requests white will work to distinguish them visually from the plan itself (the commitments), if the background is different enough?

**Comment by LeosPrograms** [comment]
I think white for the background is fine, and EEEEEE is also good for satisfy requests column.

**Comment by fosterlynn** [comment]
Lookin' good!  One small thing: The background color of the Satisfy Requests column is lighter when the plan is not saved, same as offer/reqs after the plan is saved.  Just not changed in both places.  Sorry to nitpick, but I think it is good to distinguish the Satisfy Requests column visually.

**Comment by fosterlynn** [comment]
The above was all done, and it looks a lot better.  I'd like to leave the issue open though, now that we are in Moss, we clash a bit with their styling.  Not sure if they will have options for the Moss look.  But if that is a ways off, we could do a few simple things to fit in better with their look.  I'll check in with the users about this and see what they think.

**Comment by LeosPrograms** [comment]
There will likely be an optional light and dark theme in Moss soon.

**Comment by fosterlynn** [comment]
good enough for now
