### ISSUE TITLE
After add to plan, the event icon not there

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#101]
I added two commitments to the Pick Up input column.  Both before saving, and after it comes back from the save, they do not have the icon to add an economic event.  I don't know if it shows up after picking Edit on the Plan list, I'm still timing out on that.  If it shows then, we can make this low priority or next phase.  If not, we'll need to fix it for phase 2.

(I also don't know if that is on purpose because the commitment hasn't saved yet.)

![Screenshot from 2024-03-01 14-11-41](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/f1e0922c-20ef-403c-b721-0fc78ba3de89)

**Comment by LeosPrograms** [comment]
Yes, the commitment needs to save before you can add an event to it. The
only way to fix this would be to save commitments immediately or wait to
save economic events until after saving the whole plan.

**Comment by fosterlynn** [comment]
>Yes, the commitment needs to save before you can add an event to it. The
only way to fix this would be to save commitments immediately or wait to
save economic events until after saving the whole plan.

Got it.  As long as when going back into a saved plan using Edit shows the event icon, than seems good enough, unless it becomes a problem for users.  I can also agree that we shouldn't reload the plan after a save, it takes too long.  I can't see if it works from Edit, but I'll assume it does, and close this.  Anyhow, it is all part of the bigger question of the long saves.
