### ISSUE TITLE
Improvements on logo/name display

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#12]
![Screenshot from 2023-06-14 18-21-47](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/45171f52-a05b-4a83-981b-ade0b8992ad9)

1. The logo that shows up as the point on the map is distorted to be too vertical.  Maybe take just a cut of the image.  Or even just make it the normal dot.  If normal dot, could we easily color code based on the role?  But yes, the image is cool, but also not worth a lot of time, unless the users really want it.

2. The logo that shows up inside the popup is also distorted.  We'll need to have some way to keep the ratio.  It might become an issue showing the logo and the note side by side, don't know.

3. Let's make the agent name at the top of the popup bolder and bigger, if possible.

EDIT: [Here are the original test logos](https://github.com/Carbon-Farm-Network/Requirements-Doc/issues/1#issue-1757697675) that you see on the screen print above, for comparison.

**Comment by fosterlynn** [comment]
Clarified with Laura and Evan.  

Best if the map "pins" are the role-based images that Laura picks for them.  These are coming.

The image that shows when the agent is clicked on the map, the popup, should show the image that was stored for that agent when created or updated.  We should make that optional if not too much trouble.

(Those are 2 different sets of images.)

**Comment by fosterlynn** [comment]
Another note.  I put this in the first release milestone.  But alternatively, we could just get rid of the logo/image for Agents, and format a big name in the popup on the map, for the first release.

**Comment by fosterlynn** [comment]
Yet another note.  For the map, if we can't get the images going in a way that works well, perhaps just go back to either normal map pins, or @happysalada 's images, and spread them across the roles appropriately.

**Comment by LeosPrograms** [comment]
the images are fixed in the popup, not on the map. default icon images work on the map though

**Comment by fosterlynn** [comment]
>For the map, if we can't get the images going in a way that works well, perhaps just go back to either normal map pins, or @happysalada 's images, and spread them across the roles appropriately.

Talked to Laura and Evan.  We decided to use @happysalada 's black and white images for the map instead of logos and instead of the more detailed images Laura sent.  They do work fine, and as @LeosPrograms said above, they are already plugged in as the default image.  There are 3 images, and we'll use them for the full set of roles.

Here is the full set of roles, with image.
Farm - farm
Design/Brand - designer
Scouring Mill - mill
Knitting Factory - mill
Weaving Factory - mill
Spinning Mill - mill
Shipping - (don't have one, I'll look for a small truck or @happysalada can make one)

So, the hard-coded list of roles needs to be fixed too.

**Comment by happysalada** [comment]
Lets use the truck from https://heroicons.com/
Its a nice set of free icons from the creators of tailwind

**Comment by fosterlynn** [comment]
Here's the recommended truck in svg, looks good to try: 
![truck](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/74325426-8562-461c-909a-d8e7e4ecdd5c)
