### ISSUE TITLE
Deleting payment removed other commitment

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#137]
Maybe just UI, maybe not.  I hit the delete icon on a "payment" commitment, which was attached to a production commitment (in this case it was a pickup of fiber.  Both the payment and the pickup commitment disappeared from the UI.  Looks like they are gone from the data store too, on reload.

Noting each delete icon should delete only one commitment.  If there is only one commitment left on the agreement, the agreement can be deleted too.

**Comment by LeosPrograms** [comment]
@fosterlynn Unable to replicate this bug, let me know if it happens again?

**Comment by fosterlynn** [comment]
Will check with next release and let you know :+1:

**Comment by fosterlynn** [comment]
Tried it again, it still did it.

Screen before (note this is from a bit earlier, the Gas and Truck commitment was moved to the bottom before deleting the top payment:
![Screenshot from 2024-11-18 18-26-55](https://github.com/user-attachments/assets/ec79885f-74cc-436a-9030-a197b412f5ac)

Screen after, note the offer still thinks there is a commitment for 407 lb from Lazy Acres:
![Screenshot from 2024-11-18 19-06-49](https://github.com/user-attachments/assets/25bd3a55-fd3a-4b7f-aa7d-36ff06cba2fc)
ffer still thinks there is a commitment for

**Comment by fosterlynn** [comment]
Looks good
