### ISSUE TITLE
Adding cost/payment to "outside" commitment

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#139]
1 hr

Not ready to do yet, need to revisit earlier decision to not do this on the planning page.  This would work just like any cost checkbox, so would require an offer.

**Comment by LeosPrograms** [comment]
@fosterlynn Could you provide more specs on this?

**Comment by LeosPrograms** [comment]
Should these impact the cost and requested counts?

**Comment by fosterlynn** [comment]
>Should these impact the cost and requested counts?

Good question, I'll ask the users.  I'm seeing some potential complications to the cost total on that page, and you probably are too.

**Comment by fosterlynn** [comment]
This works well now, except the "cost" line is still there on the primary commitment.  Leaving open just for that.

![Screenshot from 2024-11-18 18-57-15](https://github.com/user-attachments/assets/f1dfc301-9be7-491b-bfb9-e022cca77988)

**Comment by fosterlynn** [comment]
Per Laura, we should include all of the "outside" costs in the cost total, in this case the clean wool purchased from Imperial, and added to the spinning column.  

Side note, at some point when they have more and more inventory saved for the next year, they'll need to separate out the cost in some way.  But it is not clear right now how that would best work for them.  I think it will be easier to think about when they are running the app in production.

**Comment by fosterlynn** [comment]
Fixed.  It took quite a long time to show the reciprocal transfer on the plan page and the exchanges report, compared to other situations.  Closing, but noting, and we'll see how it works.
