### ISSUE TITLE
Facets need to be optional on object

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#28]
When presenting a dropdown of facet values for any facet, either for Agent or ResourceSpecification, there needs to be a ---- option to not choose one of the facet values in the list.  (Not all facets will be applicable for all objects.)

**Comment by fosterlynn** [comment]
This is working great on Agents, but not yet on Resource Specification.  Re-opening.

Not sure if there is any connection to https://github.com/Carbon-Farm-Network/app-carbon-farm-network/issues/7#issuecomment-1650944711.

**Comment by LeosPrograms** [comment]
they are optional but once they are assigned you can only re-assign, not remove entirely. that will require a little additional work.
