### ISSUE TITLE
CSS on title bar & page headings

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#47]
This is the main logo on the title bar.  @happysalada I offered that we could have Laura and Evan join a session, and work it through with them, where they can see changes, and say decide on the spot.

**Comment by happysalada** [comment]
That could work, ideally, pospi or leo is there to run the app locally as well to see the changes in real time.

**Comment by fosterlynn** [comment]
Here is a link from Laura, who was wondering if we could try to make the app with logo more compatible with this https://www.nycfnhub.com/.

The only thing I can think of is to make the whole title bar white like this link, and then put some kind of fat dividing line or something.  That's still a lot of white though, except for the map.  Other ideas welcome, of course.

**Comment by fosterlynn** [comment]
Here's a rough mockup for discussion, sent to Laura for feedback.
![cfn-css-mockup](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/2e7d1d3f-cbe1-4d39-8836-b91ce548bbdc)

**Comment by fosterlynn** [comment]
>Here's a rough mockup for discussion, sent to Laura for feedback.

Laura loved this.  @happysalada and I worked on it today, and he merged a version on the Planning page, since that doesn't connect to the data yet.  

The title bar should go on all pages, and maybe it does now, Raphael please clarify as needed, or it is probably clear in the code.  We moved the config pages to the dropdown menu under the person icon on the upper right, in addition to the css changes.

The page title with the background image and white text should go on every page that has a title.  The map doesn't need it, so we started a page by page thing.  But thinking about it now, it is OK if the map has it if it makes it a lot easier and cleaner to just put it on every page.  I can make something up for the map, maybe instructions.  Note that every page will have different text though.

**Comment by happysalada** [comment]
Maybe you can add a screenshot of what we did yesterday, that ought to clarify the whole thing.

**Comment by fosterlynn** [comment]
>Maybe you can add a screenshot of what we did yesterday, that ought to clarify the whole thing.

![Screenshot from 2023-08-18 10-48-37](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/8944ab91-b975-495a-8dbe-c652fc06f960)

**Comment by LeosPrograms** [comment]
I put the header on each page except map, although I did not fill in descriptions as I do not have them.
