### ISSUE TITLE
Switching agents leaves old data

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#50]
On the map, if you click on an agent so the popup is displayed, and don't X out of the popup before clicking on another agent, some data can remain.  If you X out, it works properly.

The sequence on this screenshot, seed acfn-8-27, using release as of yesterday:
1. Clicked on Lynn's Farm, which has a certification facet value and has an offer.
2. Clicked on Bob's Scouring Service, which has no certification and no offers.
3. The facet value and offer from Lynn's Farm remain on the Bob's popup.
4. Also then you cannot X out of the popup.

![Screenshot from 2023-08-27 06-31-59](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/c92a894d-ea64-4780-9948-6a7b49373d00)

**Comment by pospi** [comment]
Should be fixed in latest changes just pushed.
