### ISSUE TITLE
Agent lat/long not on Edit modal

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#54]
When editing an agent, the latitude and longitude don't come back in the modal.  I'm guessing this is because of a hack where they are saved in a string?  Also noting that at some point, we should have actual location information, as well as a more complete agent model, either in hREA or as a separate function.

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.1
