### ISSUE TITLE
Planning: Add, Edit, Delete commitments

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#63]
- [ ] Add to the UI as needed, on each commitment, including the Satisfy Requests commitments.
- [ ] Modal for the adds and edits, including the payment/cost information, which is attached to some of the production commitments.
- [ ] Saves properly

**Comment by fosterlynn** [comment]
A question on Add: Since the users want some degree of control over the sequencing of inputs and outputs, how should we do this?  We could put an "add below" + on each commitment.  We could leave the + with the process, and let the user move commitments around within a process.  (dragndrop)

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.1
