### ISSUE TITLE
Add "Network" to the list of roles

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#70]
CFN is now hard-coded to be created in a new network, which is helpful, but we also need to be able to create it as a Network in existing seeds, especially the hopefully "real" one.  So it needs to be in the hard-coded role list.  Eventually, all that will be user data driven.

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.1
