### ISSUE TITLE
Planning: Easier horizontal scrolling

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#71]
Right now, to scroll sideways on the planning page, you have to scroll down to get a scroll bar at the bottom, annoying but also hard to tell that is what you have to do.  (Ubuntu, Firefox)

Can we drag sideways?  Or have a horizontal scroll bar at all times?

**Comment by fosterlynn** [comment]
Actually, I just discovered that the left and right arrows work.  So that makes this a much  lower priority, and maybe not an issue at all, will check with Laura.

**Comment by LeosPrograms** [comment]
I can put the scroll bar on the top of the page if you want. It's unconventional but this is little bit of an unconventional ui anyway!
