### ISSUE TITLE
Error saving plan after deleting commitment

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#75]
I deleted a commitment in the plan, one that also was part of an Agreement.  (I also changed several (fixing agents).  And I edited the plan description itself.)  I got this:
![Screenshot from 2024-02-08 13-42-37](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/39e9d75e-dd28-4f83-8445-c1de6550c4d8)
![Screenshot from 2024-02-08 13-43-16](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/1e201b64-f736-40bc-abbe-4fe921c980fe)

[EDIT: I think you are doing this, but just noting in case that deleting a commitment that is part of the production plan, and also part of an agreement will require deleting the agreement and the other commitment that is part of that agreement (the payment).]

**Comment by fosterlynn** [comment]
As a note, the commitment (at least the production one) was actually deleted.  (It was the shipping service between Scour and Spin.)
![Screenshot from 2024-02-08 14-17-49](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/4890c4b0-de98-440b-b3da-5fa1b25ee10f)

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.3

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.3

**Comment by fosterlynn** [comment]
I tried this again, approximately.  What I got may or may not be the same problem.  I deleted one commitment (it was one that should have had an agreement attached, but wasn't showing the cost, so probably it didn't find it for some reason?).  The delete appeared to work before the Save.  It was the Spinning Service.
![Screenshot from 2024-02-13 14-37-55](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/7e4e6032-abba-4a99-975f-deae6e6593cc)

![Screenshot from 2024-02-13 14-38-08](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/5fcbcca7-40df-48ce-af54-a37b1a7d71c3)

On hitting Save, I get the following.   This was not the first save for the plan.  I also may have done a couple other things before the delete and save, I'm not sure (sorry, I can retest if it will help).
![Screenshot from 2024-02-13 14-40-38](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/f6500fce-378f-4302-bc28-51b3ce88d0a5)

And now I can't get out of that screen even with closing the app and the launcher.  Will try after rebooting my computer.....

**Comment by fosterlynn** [comment]
Tried again with a commitment with no cost attached, deleted one of the inputs to Spin Yarn.
![Screenshot from 2024-02-13 15-10-13](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/46f4f9ce-1740-4c8c-84aa-a1c203e75573)

Same result:
![Screenshot from 2024-02-13 15-15-24](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/dd08f66d-21f5-45d4-b77e-f004fb9fdb19)

I'm noticing that the error message refers to "Carbon Farm Network", even though I had changed the name to "Carbon Farm Net" so it would fit on one line.

**Comment by fosterlynn** [comment]
Well, I'm having the same problem with other changes now.  So need to test some different conditions cleanly, I'm not seeing consistently the same problem with the same conditions, so it is confusing.  Please wait on this until I do that.

**Comment by fosterlynn** [comment]
I'm still having a hard time teasing out the errors vs the conditions.  But it looks like the never saving problem is not about deleting a commitment.  So I'm closing this again.
