### ISSUE TITLE
Discussion: Should we save a (saved) plan edits at once?

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#76]
Looks like how it works now is that once a saved plan comes back, and changes are made, the user needs to hit the Save button to actually save their changes, it brings up the plan data (name, descr), then saves everything just done.  (Similar to how it works before the first save.)

Alternatively, it could save as each modal is saved.  And the Save button could just do the plan object itself.  Something like "Change Plan".

I don't want to make any changes that will be more work than leaving it as is.  Just bringing this up in case doing one-at-a-time saves make other things easier enough to be worth doing.

I don't have a firm opinion, putting it out for discussion if there is any.  There are UX reasons for both sides of this.

**Comment by LeosPrograms** [comment]
Since we're getting order from save time, this would mess that up.

**Comment by fosterlynn** [comment]
I'd like to understand the ordering better:
1. Are you re-saving everything whenever they hit the Save button, whether or not it was changed, to get ordering create dates?
2. We don't have a way to order new commitments they add, true?  (I'm thinking of how to do that, and it may affect how you are doing ordering; or vice versa.)

**Comment by LeosPrograms** [comment]
Yes, everything is re-saved. It seems to order correctly, even with new commitments.

**Comment by fosterlynn** [comment]
Closing this, it might be the best behavior anyhow.  We'll see if we get feedback on that.
