### ISSUE TITLE
A process shifted columns after save

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#79]
Here is before the first save, see scouring.
![Screenshot from 2024-02-08 14-46-12](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/562b9b28-a41f-4ca3-b875-9b987f9db664)

Here is when it came back after the save. One of the scouring processes moved backwards to the ship.  Note that before the save, I did delete the output that is gone from Pick Up.  I'm pretty sure that didn't cause the scour movement, at least when I did it. 
![Screenshot from 2024-02-08 15-04-35](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/e7db6297-5ffd-4445-8033-4c94203417ae)

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.3
