### ISSUE TITLE
Add export/import feature to bridge to new versions

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#82]
We decided this would be important, given the frequent loss of data from earlier versions.

When that is done, we can remove the auto generation of various data (ResourceSpecification, etc. that is maintainable in the app)  We'll still need Units, map config, anything not maintainable yet.

**Comment by fosterlynn** [comment]
The export is there, by data type (agents, offers, etc.)

**Comment by fosterlynn** [comment]
Added priority label, but the priorities are only import on offer and request.  (Agent already works.)  The rest are not priority.

**Comment by fosterlynn** [comment]
Complete.  Except the Requests import doesn't show the request list after import, so I'm leaving it open with a change to lower priority, easy workaround if you know it will happen.

**Comment by fosterlynn** [comment]
Update: What we have seems to be working.  Next up:  Finish Plan, add Economic Events and Economic Resoures.  Or whenever it makes sense, just make it into one big export and import?  Your choice.

**Comment by fosterlynn** [comment]
Earlier forgot one issue on Offers, low priority, don't need it for this milestone.  It does its job (I think), but the in progress thing never goes away.
![Screenshot from 2024-07-24 06-28-40](https://github.com/user-attachments/assets/411a0e62-dcda-4d23-893e-41cb715ccb5a)

**Comment by fosterlynn** [comment]
All the new export/imports working great except the one small thing above.  Includes plan, events.  Leaving open with no milestone, at low priority.

**Comment by LeosPrograms** [comment]
I couldn't reproduce this. I think it just takes a while to finish the offers import.
