### ISSUE TITLE
Propagate UI changes from earlier

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#83]
@happysalada did some styling and other UI changes with Laura and I.  I see those got merged, but I don't see all of them there.  Also they need to be propagated to all the pages, as appropriate.

We were working on the plan page (hitting Add Plan from the plan list).  So that's where the changes will be.

What I remember:

*    top band - upper left nytl logo bigger, maybe font changes on the title selection bar (?); also moved everything out to the edges - I think this section is the same on all pages now, so feel free to not do anything there, unless you can see changes somewhere - the only thing that doesn't look quite changed to me is the logo size, and I could be wrong
*    on the page title/description band below that, the font bigger (maybe bolder?) (it is on the plan page), the up and down width larger (it is on the plan page), a new background image (not there), moved the title over to line up on the left (is good on the plan page, not others).
*    on plan page, I think we picked new images for the column headings, will be ProcessSpecification.image eventually, but not sure where those are stored now.
*    on plan page, should be a small margin between the title background image and all the column images

**Comment by LeosPrograms** [comment]
https://github.com/Carbon-Farm-Network/app-carbon-farm-network/releases/tag/v0.2.3
