### ISSUE TITLE
Quantities showing on the plan

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#96]
At the beginning, the commitment quantities are displayed.  Adding an event changes it to the event quantity, at least when the event finishes the commitment.

Right now we are not supporting multiple events (but we will need to do that), and that will just be supported by updating the event.  But, what should show if the commitment is not finished but there is an event?  I think the commitment quantity would be best there, of those choices.

But is a better solution to keep the commitment quantity, and add another line for the event(s) quantity?  Or add it to the commitment quantity line somehow, something like "pickup 20 pound" > "pickup 20 pound (18)".  But that doesn't support other changes, like provider, which might be unlikely for CFN, but not for every group.

Needs discussion with the CFN.

**Comment by fosterlynn** [comment]
Discussion with the users:  Leave it how it is now, with event quantity replacing commitment quantity, they will see during use if they feel like they need more.

Right now I can't tell if we are allowing update of the one event, or allowing multiple events on one commitment.  Either is fine (eventually we'll want multiple events).  If we are creating multiple events now, add the quantities together for what displays on the commitment.

**Comment by LeosPrograms** [comment]
![Screenshot from 2024-03-01 09-49-27](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/18725005/ad23c42d-0b64-46ad-bfbe-6f630c521f33)
![Screenshot from 2024-03-01 10-15-18](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/18725005/852cc965-2c47-4da5-8126-fd52f874c6d0)
How is this?

**Comment by fosterlynn** [comment]
This is interesting!  Looks good to me.  

Does it work on commitments too? Or just on the offer list?

**Comment by LeosPrograms** [comment]
Just the offer list

**Comment by fosterlynn** [comment]
The line on the offers is looking good!  One small change:  If there are none available (i.e. available is N/A, basically not limited, like the services), which suppressed the available line, let's also suppress the n of n requested line.

**Comment by fosterlynn** [comment]
Tested the multiple events adding up the quantities on the commitment, looks good!

**Comment by fosterlynn** [comment]
In the screen shot above, Gray Alpaca Dirty from Farm 1 shows 34 on the pickup commitment, but does not show "34 of 44" on the offer.  But when I added a pickup or changed a pickup commitment, it did then show up on the offer correctly. So just the first time displayed it is not there.

**Comment by LeosPrograms** [comment]
I changed it to show from the beginning. However, this may be inaccurate, as the original offer is not referenced in the agreement.

Also, removed "of x" from requested line, as the availability is listed above and would be redundant.

**Comment by fosterlynn** [comment]
Good for now!
