### ISSUE TITLE
Filter actions on dropdowns on modals

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#97]
This is a "nice to have", but I don't want to wait too long, as it will help users' general understanding of how things are structured.

We can limit the action dropdowns as follows:

- On inputs to processes, Actions where `inputOutput` == `input` or `outputInput`
- On outputs to processes, Actions where `inputOutput` == `output` or `outputInput`
- On the Satisfy Requests, actually let's just use `transfer` and not give them a choice (that won't work for everyone, but it is the only thing that will work with this UI anyway) (either keep the dropdown and just have the only choice be `transfer` or just display "transfer", or even leave it off just the modal, whichever is easiest)

Note:  I don't know if the `inputOutput` behavior, and other behaviors, are in hREA.

**Comment by fosterlynn** [comment]
Looks like the actions are not up to date in the graphql spec or in hREA.  I'll do a PR for graphql for the newer behavior fields.  It may take a while for hREA.  We may want to hard-code the dropdowns as follows:

Inputs (ids): consume, use, work, cite, pickup (label `pick up`), accept, combine, deliverService (label `deliver service`).

Outputs (ids): produce, deliverService (label `deliver service`), dropoff (label `drop off`), modify, separate.

`deliverService` is probably not the id in hREA.  It is probably deliver-service.

**Comment by fosterlynn** [comment]
One more thought on this one.  Would it be easier all round to update the id and label data for the actions now in hREA, and leave the additional fields for later?  I don't know if the data is hard-coded in hREA, or loaded from script, or what.  But then we wouldn't need to make any UI changes when the whole thing gets updated in hREA.  (We would still hard-code the filters, and we could leave that.)  

If we do that, I'll track down anyone who is actually using them as-is now, most likely nobody.

But it is probably nobody, since really deliverService is the only change.  

Any actions that are on my list above, but not currently in hREA, we don't need to add if it is extra work.

**Comment by LeosPrograms** [comment]
If I take the actions from hREA and filter them as described, the lists are
input: pickup, consume, use, work, cite, accept
output: dropoff, produce, modify, pass, fail, deliver-service

**Comment by fosterlynn** [comment]
Those are pretty good lists, but let's get rid of pass and fail.  Those aren't actions any more, so whatever is easiest, but you can feel free to delete those in hREA if that is easiest.

**Comment by fosterlynn** [comment]
>Those are pretty good lists, but let's get rid of pass and fail.

On second thought, let's just not worry about pass and fail, they won't bother anyone for now.  It will work it self out as hREA is fixed.

**Comment by fosterlynn** [comment]
Good enough for now.
